//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 612 // Disable "CS0612 '...' is obsolete"
#pragma warning disable 649 // Disable "CS0649 Field is never assigned to, and will always have its default value null"
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"
#pragma warning disable 8604 // Disable "CS8604 Possible null reference argument for parameter"
#pragma warning disable 8625 // Disable "CS8625 Cannot convert null literal to non-nullable reference type"
#pragma warning disable 8765 // Disable "CS8765 Nullability of type of parameter doesn't match overridden member (possibly because of nullability attributes)."

namespace Fastdotnet.Desktop.Api.Models
{
    using System = global::System;

    

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class AdminUserDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("Id")]
        public string Id { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Username")]
        public string Username { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Name")]
        public string Name { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Email")]
        public string Email { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Phone")]
        public string Phone { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("IsActive")]
        public bool IsActive { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("LastLoginTime")]
        public System.DateTimeOffset? LastLoginTime { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("LastLoginIp")]
        public string LastLoginIp { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("CreateTime")]
        public System.DateTimeOffset CreateTime { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Avatar")]
        public string Avatar { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("RoleIds")]
        public System.Collections.Generic.ICollection<string> RoleIds { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Buttons")]
        public System.Collections.Generic.ICollection<string> Buttons { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class AdminUserDtoPageResult
    {

        [System.Text.Json.Serialization.JsonPropertyName("PageInfo")]
        public PageInfo PageInfo { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Items")]
        public System.Collections.Generic.ICollection<AdminUserDto> Items { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ApiResult
    {

        [System.Text.Json.Serialization.JsonPropertyName("Code")]
        public int Code { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Msg")]
        public string Msg { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class AppRegisterDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("Username")]
        [System.ComponentModel.DataAnnotations.Required]
        public string Username { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Password")]
        [System.ComponentModel.DataAnnotations.Required]
        public string Password { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Email")]
        [System.ComponentModel.DataAnnotations.Required]
        public string Email { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("VerificationCode")]
        [System.ComponentModel.DataAnnotations.Required]
        public string VerificationCode { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class AssignPermissionsDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("PermissionIds")]
        public System.Collections.Generic.ICollection<string> PermissionIds { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CodeGenConfigDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("Id")]
        public string Id { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("TableName")]
        public string TableName { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("EntityName")]
        public string EntityName { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("NameSpace")]
        public string NameSpace { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("AuthorName")]
        public string AuthorName { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("GenerateType")]
        public string GenerateType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("GenerateMenu")]
        public bool GenerateMenu { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("MenuIcon")]
        public string MenuIcon { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("MenuPid")]
        public string MenuPid { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("PagePath")]
        public string PagePath { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("PrintType")]
        public string PrintType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("PrintName")]
        public string PrintName { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("TableUniqueList")]
        public System.Collections.Generic.ICollection<TableUniqueConfigDto> TableUniqueList { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CodeGenConfigDtoPageResult
    {

        [System.Text.Json.Serialization.JsonPropertyName("PageInfo")]
        public PageInfo PageInfo { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Items")]
        public System.Collections.Generic.ICollection<CodeGenConfigDto> Items { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CodeGenInput
    {

        [System.Text.Json.Serialization.JsonPropertyName("ConfigId")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(100)]
        public string ConfigId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("TableName")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(100)]
        public string TableName { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("BusName")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(100)]
        public string BusName { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("NameSpace")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(200)]
        public string NameSpace { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("AuthorName")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(50)]
        public string AuthorName { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("GenerateType")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(50)]
        public string GenerateType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("GenerateMenu")]
        public bool GenerateMenu { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("MenuIcon")]
        [System.ComponentModel.DataAnnotations.StringLength(100)]
        public string MenuIcon { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("MenuPid")]
        [System.ComponentModel.DataAnnotations.StringLength(100)]
        public string MenuPid { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("PagePath")]
        [System.ComponentModel.DataAnnotations.StringLength(200)]
        public string PagePath { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ColumnInfoDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("ColumnName")]
        public string ColumnName { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("PropertyName")]
        public string PropertyName { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("DataType")]
        public string DataType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("NetType")]
        public string NetType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("IsPrimarykey")]
        public bool IsPrimarykey { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("IsIdentity")]
        public bool IsIdentity { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("IsNullable")]
        public bool IsNullable { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Length")]
        public int Length { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Scale")]
        public int? Scale { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("DefaultValue")]
        public string DefaultValue { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("ColumnComment")]
        public string ColumnComment { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("IsIgnore")]
        public bool IsIgnore { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CreateAdminUserDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("Username")]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.StringLength(50, MinimumLength = 3)]
        public string Username { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Password")]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.StringLength(100, MinimumLength = 6)]
        public string Password { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Name")]
        public string Name { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Email")]
        public string Email { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Phone")]
        public string Phone { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("IsActive")]
        public bool IsActive { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Avatar")]
        public string Avatar { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CreateCodeGenDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("TableName")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(100)]
        public string TableName { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("NameSpace")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(200)]
        public string NameSpace { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("GenerateType")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(50)]
        public string GenerateType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("GenerateMenu")]
        public bool GenerateMenu { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("MenuIcon")]
        public string MenuIcon { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("MenuPid")]
        public string MenuPid { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("PagePath")]
        public string PagePath { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("PrintType")]
        public string PrintType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("PrintName")]
        public string PrintName { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("TableUniqueList")]
        public System.Collections.Generic.ICollection<TableUniqueConfigDto> TableUniqueList { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CreateEmailConfigDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("Host")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(200)]
        public string Host { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Port")]
        public int Port { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Username")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(200)]
        public string Username { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Password")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(200)]
        public string Password { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("SenderEmail")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(200)]
        public string SenderEmail { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("SenderName")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(200)]
        public string SenderName { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("EnableSsl")]
        public bool EnableSsl { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CreateFdBlacklistDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("Type")]
        [System.ComponentModel.DataAnnotations.Required]
        public string Type { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Value")]
        [System.ComponentModel.DataAnnotations.Required]
        public string Value { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Reason")]
        public string Reason { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("ExpiredAt")]
        public System.DateTimeOffset? ExpiredAt { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CreateFdCodeGenConfigDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("CodeGenId")]
        public long CodeGenId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("ColumnName")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(128)]
        public string ColumnName { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("ColumnKey")]
        [System.ComponentModel.DataAnnotations.StringLength(8)]
        public string ColumnKey { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("PropertyName")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(128)]
        public string PropertyName { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("ColumnLength")]
        public int ColumnLength { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("ColumnComment")]
        [System.ComponentModel.DataAnnotations.StringLength(128)]
        public string ColumnComment { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("DataType")]
        [System.ComponentModel.DataAnnotations.StringLength(64)]
        public string DataType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("NetType")]
        [System.ComponentModel.DataAnnotations.StringLength(64)]
        public string NetType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("DefaultValue")]
        public string DefaultValue { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("EffectType")]
        [System.ComponentModel.DataAnnotations.StringLength(64)]
        public string EffectType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("FkConfigId")]
        [System.ComponentModel.DataAnnotations.StringLength(20)]
        public string FkConfigId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("FkEntityName")]
        [System.ComponentModel.DataAnnotations.StringLength(64)]
        public string FkEntityName { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("FkTableName")]
        [System.ComponentModel.DataAnnotations.StringLength(128)]
        public string FkTableName { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("FkDisplayColumns")]
        [System.ComponentModel.DataAnnotations.StringLength(64)]
        public string FkDisplayColumns { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("FkLinkColumnName")]
        [System.ComponentModel.DataAnnotations.StringLength(64)]
        public string FkLinkColumnName { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("FkColumnNetType")]
        [System.ComponentModel.DataAnnotations.StringLength(64)]
        public string FkColumnNetType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("PidColumn")]
        [System.ComponentModel.DataAnnotations.StringLength(128)]
        public string PidColumn { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("DictTypeCode")]
        [System.ComponentModel.DataAnnotations.StringLength(64)]
        public string DictTypeCode { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("QueryType")]
        [System.ComponentModel.DataAnnotations.StringLength(16)]
        public string QueryType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("WhetherQuery")]
        [System.ComponentModel.DataAnnotations.StringLength(8)]
        public string WhetherQuery { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("WhetherRetract")]
        [System.ComponentModel.DataAnnotations.StringLength(8)]
        public string WhetherRetract { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("WhetherRequired")]
        [System.ComponentModel.DataAnnotations.StringLength(8)]
        public string WhetherRequired { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("WhetherSortable")]
        [System.ComponentModel.DataAnnotations.StringLength(8)]
        public string WhetherSortable { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("WhetherTable")]
        [System.ComponentModel.DataAnnotations.StringLength(8)]
        public string WhetherTable { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("WhetherAddUpdate")]
        [System.ComponentModel.DataAnnotations.StringLength(8)]
        public string WhetherAddUpdate { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("WhetherImport")]
        [System.ComponentModel.DataAnnotations.StringLength(8)]
        public string WhetherImport { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("WhetherCommon")]
        [System.ComponentModel.DataAnnotations.StringLength(8)]
        public string WhetherCommon { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("OrderNo")]
        public int OrderNo { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CreateFdRateLimitRuleDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("Type")]
        [System.ComponentModel.DataAnnotations.Required]
        public string Type { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Key")]
        [System.ComponentModel.DataAnnotations.Required]
        public string Key { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("PermitLimit")]
        [System.ComponentModel.DataAnnotations.Range(1, 2147483647)]
        public int PermitLimit { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("WindowSeconds")]
        [System.ComponentModel.DataAnnotations.Range(1, 2147483647)]
        public int WindowSeconds { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Description")]
        public string Description { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CreateFdFdMenuButtonDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("Name")]
        public string Name { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Code")]
        public string Code { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Description")]
        public string Description { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("MenuCode")]
        public string MenuCode { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Module")]
        public string Module { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Category")]
        public string Category { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Sort")]
        public int Sort { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("PermissionCode")]
        public string PermissionCode { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("IsEnabled")]
        public bool IsEnabled { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CreateFdMenuDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("Name")]
        public string Name { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Path")]
        public string Path { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Icon")]
        public string Icon { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("ParentCode")]
        public string ParentCode { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Sort")]
        public int Sort { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Type")]
        public MenuType Type { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Module")]
        public string Module { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Category")]
        public string Category { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("IsExternal")]
        public bool IsExternal { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("ExternalUrl")]
        public string ExternalUrl { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("IsEnabled")]
        public bool IsEnabled { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("PermissionCode")]
        public string PermissionCode { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Component")]
        public string Component { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("IsHide")]
        public bool IsHide { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("IsKeepAlive")]
        public bool IsKeepAlive { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("IsAffix")]
        public bool IsAffix { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("IsIframe")]
        public bool IsIframe { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("IsFdMicroApp")]
        public bool IsFdMicroApp { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("isLink")]
        public bool IsLink { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CreateFdRoleDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("Name")]
        [System.ComponentModel.DataAnnotations.Required]
        public string Name { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Description")]
        public string Description { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Category")]
        [System.ComponentModel.DataAnnotations.Required]
        public string Category { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class EmailConfigBooleanFuncExpression
    {

        [System.Text.Json.Serialization.JsonPropertyName("Type")]
        public string Type { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("NodeType")]
        public ExpressionType NodeType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Parameters")]
        public System.Collections.Generic.ICollection<ParameterExpression> Parameters { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Name")]
        public string Name { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Body")]
        public Expression Body { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("ReturnType")]
        public string ReturnType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("TailCall")]
        public bool TailCall { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("CanReduce")]
        public bool CanReduce { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class EmailConfigDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("Id")]
        public string Id { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Host")]
        public string Host { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Port")]
        public int Port { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Username")]
        public string Username { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Password")]
        public string Password { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("SenderEmail")]
        public string SenderEmail { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("SenderName")]
        public string SenderName { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("EnableSsl")]
        public bool EnableSsl { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class EmailConfigDtoPageResult
    {

        [System.Text.Json.Serialization.JsonPropertyName("PageInfo")]
        public PageInfo PageInfo { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Items")]
        public System.Collections.Generic.ICollection<EmailConfigDto> Items { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Expression
    {

        [System.Text.Json.Serialization.JsonPropertyName("NodeType")]
        public ExpressionType NodeType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Type")]
        public string Type { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("CanReduce")]
        public bool CanReduce { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum ExpressionType
    {

        _0 = 0,

        _1 = 1,

        _2 = 2,

        _3 = 3,

        _4 = 4,

        _5 = 5,

        _6 = 6,

        _7 = 7,

        _8 = 8,

        _9 = 9,

        _10 = 10,

        _11 = 11,

        _12 = 12,

        _13 = 13,

        _14 = 14,

        _15 = 15,

        _16 = 16,

        _17 = 17,

        _18 = 18,

        _19 = 19,

        _20 = 20,

        _21 = 21,

        _22 = 22,

        _23 = 23,

        _24 = 24,

        _25 = 25,

        _26 = 26,

        _27 = 27,

        _28 = 28,

        _29 = 29,

        _30 = 30,

        _31 = 31,

        _32 = 32,

        _33 = 33,

        _34 = 34,

        _35 = 35,

        _36 = 36,

        _37 = 37,

        _38 = 38,

        _39 = 39,

        _40 = 40,

        _41 = 41,

        _42 = 42,

        _43 = 43,

        _44 = 44,

        _45 = 45,

        _46 = 46,

        _47 = 47,

        _48 = 48,

        _49 = 49,

        _50 = 50,

        _51 = 51,

        _52 = 52,

        _53 = 53,

        _54 = 54,

        _55 = 55,

        _56 = 56,

        _57 = 57,

        _58 = 58,

        _59 = 59,

        _60 = 60,

        _61 = 61,

        _62 = 62,

        _63 = 63,

        _64 = 64,

        _65 = 65,

        _66 = 66,

        _67 = 67,

        _68 = 68,

        _69 = 69,

        _70 = 70,

        _71 = 71,

        _72 = 72,

        _73 = 73,

        _74 = 74,

        _75 = 75,

        _76 = 76,

        _77 = 77,

        _78 = 78,

        _79 = 79,

        _80 = 80,

        _81 = 81,

        _82 = 82,

        _83 = 83,

        _84 = 84,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class FdAdminUserBooleanFuncExpression
    {

        [System.Text.Json.Serialization.JsonPropertyName("Type")]
        public string Type { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("NodeType")]
        public ExpressionType NodeType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Parameters")]
        public System.Collections.Generic.ICollection<ParameterExpression> Parameters { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Name")]
        public string Name { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Body")]
        public Expression Body { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("ReturnType")]
        public string ReturnType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("TailCall")]
        public bool TailCall { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("CanReduce")]
        public bool CanReduce { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class FdBlacklistBooleanFuncExpression
    {

        [System.Text.Json.Serialization.JsonPropertyName("Type")]
        public string Type { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("NodeType")]
        public ExpressionType NodeType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Parameters")]
        public System.Collections.Generic.ICollection<ParameterExpression> Parameters { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Name")]
        public string Name { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Body")]
        public Expression Body { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("ReturnType")]
        public string ReturnType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("TailCall")]
        public bool TailCall { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("CanReduce")]
        public bool CanReduce { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class FdBlacklistDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("Id")]
        public long Id { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Type")]
        [System.ComponentModel.DataAnnotations.Required]
        public string Type { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Value")]
        [System.ComponentModel.DataAnnotations.Required]
        public string Value { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Reason")]
        public string Reason { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("ExpiredAt")]
        public System.DateTimeOffset? ExpiredAt { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("IsSystem")]
        public bool IsSystem { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("CreateTime")]
        public System.DateTimeOffset CreateTime { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("UpdateTime")]
        public System.DateTimeOffset? UpdateTime { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("IsDeleted")]
        public bool IsDeleted { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class FdBlacklistDtoPageResult
    {

        [System.Text.Json.Serialization.JsonPropertyName("PageInfo")]
        public PageInfo PageInfo { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Items")]
        public System.Collections.Generic.ICollection<FdBlacklistDto> Items { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class FdCodeGenBooleanFuncExpression
    {

        [System.Text.Json.Serialization.JsonPropertyName("Type")]
        public string Type { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("NodeType")]
        public ExpressionType NodeType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Parameters")]
        public System.Collections.Generic.ICollection<ParameterExpression> Parameters { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Name")]
        public string Name { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Body")]
        public Expression Body { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("ReturnType")]
        public string ReturnType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("TailCall")]
        public bool TailCall { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("CanReduce")]
        public bool CanReduce { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class FdCodeGenConfigBooleanFuncExpression
    {

        [System.Text.Json.Serialization.JsonPropertyName("Type")]
        public string Type { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("NodeType")]
        public ExpressionType NodeType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Parameters")]
        public System.Collections.Generic.ICollection<ParameterExpression> Parameters { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Name")]
        public string Name { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Body")]
        public Expression Body { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("ReturnType")]
        public string ReturnType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("TailCall")]
        public bool TailCall { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("CanReduce")]
        public bool CanReduce { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class FdCodeGenConfigDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("Id")]
        public string Id { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("CodeGenId")]
        public long CodeGenId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("ColumnName")]
        public string ColumnName { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("ColumnKey")]
        public string ColumnKey { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("PropertyName")]
        public string PropertyName { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("ColumnLength")]
        public int ColumnLength { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("ColumnComment")]
        public string ColumnComment { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("DataType")]
        public string DataType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("NetType")]
        public string NetType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("DefaultValue")]
        public string DefaultValue { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("EffectType")]
        public string EffectType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("FkConfigId")]
        public string FkConfigId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("FkEntityName")]
        public string FkEntityName { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("FkTableName")]
        public string FkTableName { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("FkDisplayColumns")]
        public string FkDisplayColumns { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("FkLinkColumnName")]
        public string FkLinkColumnName { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("FkColumnNetType")]
        public string FkColumnNetType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("PidColumn")]
        public string PidColumn { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("DictTypeCode")]
        public string DictTypeCode { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("QueryType")]
        public string QueryType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("WhetherQuery")]
        public string WhetherQuery { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("WhetherRetract")]
        public string WhetherRetract { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("WhetherRequired")]
        public string WhetherRequired { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("WhetherSortable")]
        public string WhetherSortable { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("WhetherTable")]
        public string WhetherTable { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("WhetherAddUpdate")]
        public string WhetherAddUpdate { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("WhetherImport")]
        public string WhetherImport { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("WhetherCommon")]
        public string WhetherCommon { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("OrderNo")]
        public int OrderNo { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class FdCodeGenConfigDtoPageResult
    {

        [System.Text.Json.Serialization.JsonPropertyName("PageInfo")]
        public PageInfo PageInfo { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Items")]
        public System.Collections.Generic.ICollection<FdCodeGenConfigDto> Items { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class FdMenuBooleanFuncExpression
    {

        [System.Text.Json.Serialization.JsonPropertyName("Type")]
        public string Type { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("NodeType")]
        public ExpressionType NodeType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Parameters")]
        public System.Collections.Generic.ICollection<ParameterExpression> Parameters { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Name")]
        public string Name { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Body")]
        public Expression Body { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("ReturnType")]
        public string ReturnType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("TailCall")]
        public bool TailCall { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("CanReduce")]
        public bool CanReduce { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class FdMenuButtonBooleanFuncExpression
    {

        [System.Text.Json.Serialization.JsonPropertyName("Type")]
        public string Type { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("NodeType")]
        public ExpressionType NodeType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Parameters")]
        public System.Collections.Generic.ICollection<ParameterExpression> Parameters { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Name")]
        public string Name { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Body")]
        public Expression Body { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("ReturnType")]
        public string ReturnType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("TailCall")]
        public bool TailCall { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("CanReduce")]
        public bool CanReduce { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class FdRateLimitRuleBooleanFuncExpression
    {

        [System.Text.Json.Serialization.JsonPropertyName("Type")]
        public string Type { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("NodeType")]
        public ExpressionType NodeType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Parameters")]
        public System.Collections.Generic.ICollection<ParameterExpression> Parameters { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Name")]
        public string Name { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Body")]
        public Expression Body { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("ReturnType")]
        public string ReturnType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("TailCall")]
        public bool TailCall { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("CanReduce")]
        public bool CanReduce { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class FdRateLimitRuleDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("Id")]
        public long Id { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Type")]
        [System.ComponentModel.DataAnnotations.Required]
        public string Type { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Key")]
        [System.ComponentModel.DataAnnotations.Required]
        public string Key { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("PermitLimit")]
        public int PermitLimit { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("WindowSeconds")]
        public int WindowSeconds { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Description")]
        public string Description { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("IsSystem")]
        public bool IsSystem { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("CreatedAt")]
        public System.DateTimeOffset CreatedAt { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("UpdatedAt")]
        public System.DateTimeOffset? UpdatedAt { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("IsDeleted")]
        public bool IsDeleted { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class FdRateLimitRuleDtoPageResult
    {

        [System.Text.Json.Serialization.JsonPropertyName("PageInfo")]
        public PageInfo PageInfo { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Items")]
        public System.Collections.Generic.ICollection<FdRateLimitRuleDto> Items { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class FdRoleBooleanFuncExpression
    {

        [System.Text.Json.Serialization.JsonPropertyName("Type")]
        public string Type { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("NodeType")]
        public ExpressionType NodeType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Parameters")]
        public System.Collections.Generic.ICollection<ParameterExpression> Parameters { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Name")]
        public string Name { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Body")]
        public Expression Body { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("ReturnType")]
        public string ReturnType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("TailCall")]
        public bool TailCall { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("CanReduce")]
        public bool CanReduce { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class LoginDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("Username")]
        [System.ComponentModel.DataAnnotations.Required]
        public string Username { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Password")]
        [System.ComponentModel.DataAnnotations.Required]
        public string Password { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("CaptchaId")]
        public string CaptchaId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("CaptchaCode")]
        public string CaptchaCode { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class LoginResultDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("Token")]
        public string Token { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class FdMenuButtonDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("Id")]
        public string Id { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Name")]
        public string Name { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Code")]
        public string Code { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Description")]
        public string Description { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("MenuCode")]
        public string MenuCode { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Module")]
        public string Module { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Category")]
        public string Category { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Sort")]
        public int Sort { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("PermissionCode")]
        public string PermissionCode { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("IsEnabled")]
        public bool IsEnabled { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class FdMenuButtonDtoPageResult
    {

        [System.Text.Json.Serialization.JsonPropertyName("PageInfo")]
        public PageInfo PageInfo { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Items")]
        public System.Collections.Generic.ICollection<FdMenuButtonDto> Items { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class MenuDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("Id")]
        public string Id { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Name")]
        public string Name { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Code")]
        public string Code { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Path")]
        public string Path { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Icon")]
        public string Icon { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("ParentCode")]
        public string ParentCode { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Sort")]
        public int Sort { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Type")]
        public MenuType Type { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Module")]
        public string Module { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Category")]
        public string Category { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("IsExternal")]
        public bool IsExternal { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("ExternalUrl")]
        public string ExternalUrl { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("IsEnabled")]
        public bool IsEnabled { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("PermissionCode")]
        public string PermissionCode { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Component")]
        public string Component { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("PluginId")]
        public string PluginId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("IsHide")]
        public bool IsHide { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("IsKeepAlive")]
        public bool IsKeepAlive { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("IsAffix")]
        public bool IsAffix { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("IsIframe")]
        public bool IsIframe { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("IsFdMicroApp")]
        public bool IsFdMicroApp { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("isLink")]
        public bool IsLink { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Children")]
        public System.Collections.Generic.ICollection<MenuDto> Children { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class MenuDtoPageResult
    {

        [System.Text.Json.Serialization.JsonPropertyName("PageInfo")]
        public PageInfo PageInfo { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Items")]
        public System.Collections.Generic.ICollection<MenuDto> Items { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum MenuType
    {

        _0 = 0,

        _1 = 1,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class PageInfo
    {

        [System.Text.Json.Serialization.JsonPropertyName("Total")]
        public int Total { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("TotalPages")]
        public int TotalPages { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("HasPreviousPage")]
        public bool HasPreviousPage { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("HasNextPage")]
        public bool HasNextPage { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Page")]
        public int Page { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("PageSize")]
        public int PageSize { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class PageQueryByConditionDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("PageIndex")]
        public int PageIndex { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("PageSize")]
        public int PageSize { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Keyword")]
        public string Keyword { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("DynamicQuery")]
        public string DynamicQuery { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("QueryParameters")]
        public System.Collections.Generic.ICollection<object> QueryParameters { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ParameterExpression
    {

        [System.Text.Json.Serialization.JsonPropertyName("Type")]
        public string Type { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("NodeType")]
        public ExpressionType NodeType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Name")]
        public string Name { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("IsByRef")]
        public bool IsByRef { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("CanReduce")]
        public bool CanReduce { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class PermissionDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("Id")]
        public string Id { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Name")]
        public string Name { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Code")]
        public string Code { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Description")]
        public string Description { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Module")]
        public string Module { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Type")]
        public string Type { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Category")]
        public string Category { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class PluginConfig
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public string Id { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string Name { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("description")]
        public string Description { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("version")]
        public string Version { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("enabled")]
        public bool Enabled { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("author")]
        public string Author { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("dependencies")]
        public System.Collections.Generic.ICollection<string> Dependencies { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("tags")]
        public System.Collections.Generic.ICollection<string> Tags { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("entryPoint")]
        public string EntryPoint { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ResetPasswordDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("NewPassword")]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.StringLength(100, MinimumLength = 6)]
        public string NewPassword { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class FdRoleDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("Id")]
        public string Id { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Name")]
        public string Name { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Code")]
        public string Code { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Description")]
        public string Description { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Category")]
        public string Category { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("IsSystem")]
        public bool IsSystem { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("CreateTime")]
        public System.DateTimeOffset CreateTime { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class FdRoleDtoPageResult
    {

        [System.Text.Json.Serialization.JsonPropertyName("PageInfo")]
        public PageInfo PageInfo { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Items")]
        public System.Collections.Generic.ICollection<FdRoleDto> Items { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class SendRegistrationCodeDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("Email")]
        [System.ComponentModel.DataAnnotations.Required]
        public string Email { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class SystemConfigBooleanFuncExpression
    {

        [System.Text.Json.Serialization.JsonPropertyName("Type")]
        public string Type { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("NodeType")]
        public ExpressionType NodeType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Parameters")]
        public System.Collections.Generic.ICollection<ParameterExpression> Parameters { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Name")]
        public string Name { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Body")]
        public Expression Body { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("ReturnType")]
        public string ReturnType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("TailCall")]
        public bool TailCall { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("CanReduce")]
        public bool CanReduce { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class FdSystemInfoConfigDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("Id")]
        public string Id { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Name")]
        public string Name { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Code")]
        public string Code { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Value")]
        public object Value { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Description")]
        public string Description { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("IsSystem")]
        public bool IsSystem { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class FdSystemInfoConfigDtoBatchUpdateByConditionDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("Query")]
        public PageQueryByConditionDto Query { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Dto")]
        public FdSystemInfoConfigDto Dto { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class FdSystemInfoConfigDtoPageResult
    {

        [System.Text.Json.Serialization.JsonPropertyName("PageInfo")]
        public PageInfo PageInfo { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Items")]
        public System.Collections.Generic.ICollection<FdSystemInfoConfigDto> Items { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class TableInfoDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("TableName")]
        public string TableName { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("EntityName")]
        public string EntityName { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("TableComment")]
        public string TableComment { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class TableUniqueConfigDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("Columns")]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.MinLength(1)]
        public System.Collections.Generic.ICollection<string> Columns { get; set; } = new System.Collections.ObjectModel.Collection<string>();

        [System.Text.Json.Serialization.JsonPropertyName("Message")]
        [System.ComponentModel.DataAnnotations.StringLength(200)]
        public string Message { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class UnlockDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("Password")]
        [System.ComponentModel.DataAnnotations.Required]
        public string Password { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class UpdateAdminUserDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("Name")]
        public string Name { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Email")]
        public string Email { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Phone")]
        public string Phone { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("IsActive")]
        public bool? IsActive { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Avatar")]
        public string Avatar { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class UpdateAdminUserDtoBatchUpdateByConditionDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("Query")]
        public PageQueryByConditionDto Query { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Dto")]
        public UpdateAdminUserDto Dto { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class UpdateCodeGenDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("TableName")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(100)]
        public string TableName { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("EntityName")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(100)]
        public string EntityName { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("NameSpace")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(200)]
        public string NameSpace { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("GenerateType")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(50)]
        public string GenerateType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("GenerateMenu")]
        public bool GenerateMenu { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("MenuIcon")]
        public string MenuIcon { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("MenuPid")]
        public string MenuPid { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("PagePath")]
        public string PagePath { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("PrintType")]
        public string PrintType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("PrintName")]
        public string PrintName { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("TableUniqueList")]
        public System.Collections.Generic.ICollection<TableUniqueConfigDto> TableUniqueList { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class UpdateCodeGenDtoBatchUpdateByConditionDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("Query")]
        public PageQueryByConditionDto Query { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Dto")]
        public UpdateCodeGenDto Dto { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class UpdateEmailConfigDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("Host")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(200)]
        public string Host { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Port")]
        public int Port { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Username")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(200)]
        public string Username { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Password")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(200)]
        public string Password { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("SenderEmail")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(200)]
        public string SenderEmail { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("SenderName")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(200)]
        public string SenderName { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("EnableSsl")]
        public bool EnableSsl { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class UpdateEmailConfigDtoBatchUpdateByConditionDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("Query")]
        public PageQueryByConditionDto Query { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Dto")]
        public UpdateEmailConfigDto Dto { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class UpdateFdBlacklistDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("Type")]
        [System.ComponentModel.DataAnnotations.Required]
        public string Type { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Value")]
        [System.ComponentModel.DataAnnotations.Required]
        public string Value { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Reason")]
        public string Reason { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("ExpiredAt")]
        public System.DateTimeOffset? ExpiredAt { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class UpdateFdBlacklistDtoBatchUpdateByConditionDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("Query")]
        public PageQueryByConditionDto Query { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Dto")]
        public UpdateFdBlacklistDto Dto { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class UpdateFdCodeGenConfigDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("CodeGenId")]
        public long CodeGenId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("ColumnName")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(128)]
        public string ColumnName { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("ColumnKey")]
        [System.ComponentModel.DataAnnotations.StringLength(8)]
        public string ColumnKey { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("PropertyName")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(128)]
        public string PropertyName { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("ColumnLength")]
        public int ColumnLength { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("ColumnComment")]
        [System.ComponentModel.DataAnnotations.StringLength(128)]
        public string ColumnComment { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("DataType")]
        [System.ComponentModel.DataAnnotations.StringLength(64)]
        public string DataType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("NetType")]
        [System.ComponentModel.DataAnnotations.StringLength(64)]
        public string NetType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("DefaultValue")]
        public string DefaultValue { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("EffectType")]
        [System.ComponentModel.DataAnnotations.StringLength(64)]
        public string EffectType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("FkConfigId")]
        [System.ComponentModel.DataAnnotations.StringLength(20)]
        public string FkConfigId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("FkEntityName")]
        [System.ComponentModel.DataAnnotations.StringLength(64)]
        public string FkEntityName { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("FkTableName")]
        [System.ComponentModel.DataAnnotations.StringLength(128)]
        public string FkTableName { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("FkDisplayColumns")]
        [System.ComponentModel.DataAnnotations.StringLength(64)]
        public string FkDisplayColumns { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("FkLinkColumnName")]
        [System.ComponentModel.DataAnnotations.StringLength(64)]
        public string FkLinkColumnName { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("FkColumnNetType")]
        [System.ComponentModel.DataAnnotations.StringLength(64)]
        public string FkColumnNetType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("PidColumn")]
        [System.ComponentModel.DataAnnotations.StringLength(128)]
        public string PidColumn { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("DictTypeCode")]
        [System.ComponentModel.DataAnnotations.StringLength(64)]
        public string DictTypeCode { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("QueryType")]
        [System.ComponentModel.DataAnnotations.StringLength(16)]
        public string QueryType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("WhetherQuery")]
        [System.ComponentModel.DataAnnotations.StringLength(8)]
        public string WhetherQuery { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("WhetherRetract")]
        [System.ComponentModel.DataAnnotations.StringLength(8)]
        public string WhetherRetract { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("WhetherRequired")]
        [System.ComponentModel.DataAnnotations.StringLength(8)]
        public string WhetherRequired { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("WhetherSortable")]
        [System.ComponentModel.DataAnnotations.StringLength(8)]
        public string WhetherSortable { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("WhetherTable")]
        [System.ComponentModel.DataAnnotations.StringLength(8)]
        public string WhetherTable { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("WhetherAddUpdate")]
        [System.ComponentModel.DataAnnotations.StringLength(8)]
        public string WhetherAddUpdate { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("WhetherImport")]
        [System.ComponentModel.DataAnnotations.StringLength(8)]
        public string WhetherImport { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("WhetherCommon")]
        [System.ComponentModel.DataAnnotations.StringLength(8)]
        public string WhetherCommon { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("OrderNo")]
        public int OrderNo { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class UpdateFdCodeGenConfigDtoBatchUpdateByConditionDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("Query")]
        public PageQueryByConditionDto Query { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Dto")]
        public UpdateFdCodeGenConfigDto Dto { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class UpdateFdRateLimitRuleDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("Type")]
        [System.ComponentModel.DataAnnotations.Required]
        public string Type { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Key")]
        [System.ComponentModel.DataAnnotations.Required]
        public string Key { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("PermitLimit")]
        [System.ComponentModel.DataAnnotations.Range(1, 2147483647)]
        public int PermitLimit { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("WindowSeconds")]
        [System.ComponentModel.DataAnnotations.Range(1, 2147483647)]
        public int WindowSeconds { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Description")]
        public string Description { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class UpdateFdRateLimitRuleDtoBatchUpdateByConditionDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("Query")]
        public PageQueryByConditionDto Query { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Dto")]
        public UpdateFdRateLimitRuleDto Dto { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class UpdateFdFdMenuButtonDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("Name")]
        public string Name { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Code")]
        public string Code { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Description")]
        public string Description { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("MenuCode")]
        public string MenuCode { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Module")]
        public string Module { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Category")]
        public string Category { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Sort")]
        public int Sort { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("PermissionCode")]
        public string PermissionCode { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("IsEnabled")]
        public bool IsEnabled { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class UpdateFdFdMenuButtonDtoBatchUpdateByConditionDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("Query")]
        public PageQueryByConditionDto Query { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Dto")]
        public UpdateFdFdMenuButtonDto Dto { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class UpdateFdMenuDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("Name")]
        public string Name { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Code")]
        public string Code { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Path")]
        public string Path { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Icon")]
        public string Icon { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("ParentCode")]
        public string ParentCode { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Sort")]
        public int Sort { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Type")]
        public MenuType Type { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Module")]
        public string Module { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Category")]
        public string Category { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("IsExternal")]
        public bool IsExternal { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("ExternalUrl")]
        public string ExternalUrl { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("IsEnabled")]
        public bool IsEnabled { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("PermissionCode")]
        public string PermissionCode { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Component")]
        public string Component { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("IsHide")]
        public bool IsHide { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("IsKeepAlive")]
        public bool IsKeepAlive { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("IsAffix")]
        public bool IsAffix { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("IsFdMicroApp")]
        public bool IsFdMicroApp { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("IsIframe")]
        public bool IsIframe { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("isLink")]
        public bool IsLink { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class UpdateFdMenuDtoBatchUpdateByConditionDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("Query")]
        public PageQueryByConditionDto Query { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Dto")]
        public UpdateFdMenuDto Dto { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class UpdateFdRoleDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("Name")]
        [System.ComponentModel.DataAnnotations.Required]
        public string Name { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Description")]
        public string Description { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class UpdateFdRoleDtoBatchUpdateByConditionDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("Query")]
        public PageQueryByConditionDto Query { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Dto")]
        public UpdateFdRoleDto Dto { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class FileResponse : System.IDisposable
    {
        private System.IDisposable _client;
        private System.IDisposable _response;

        public int StatusCode { get; private set; }

        public System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> Headers { get; private set; }

        public System.IO.Stream Stream { get; private set; }

        public bool IsPartial
        {
            get { return StatusCode == 206; }
        }

        public FileResponse(int statusCode, System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> headers, System.IO.Stream stream, System.IDisposable client, System.IDisposable response)
        {
            StatusCode = statusCode;
            Headers = headers;
            Stream = stream;
            _client = client;
            _response = response;
        }

        public void Dispose()
        {
            Stream.Dispose();
            if (_response != null)
                _response.Dispose();
            if (_client != null)
                _client.Dispose();
        }
    }



}

#pragma warning restore  108
#pragma warning restore  114
#pragma warning restore  472
#pragma warning restore  612
#pragma warning restore 1573
#pragma warning restore 1591
#pragma warning restore 8073
#pragma warning restore 3016
#pragma warning restore 8603
#pragma warning restore 8604
#pragma warning restore 8625